### ISSUE TITLE
Tech stack

### ISSUE THREAD

**Issue by prateekbh** [riot/made-with-riot#2]
This is to discuss what we use for made-with-riot...
For sure Riot :D
but open pieces remain AjaxCalls...?
where we store submitted projects...?
backend?
do we adapt a Flux implementation?(i prefer)
any css framework?
Iso-morphic stack? (for SEO)
what do we do for critical CSS?

**Comment by GianlucaGuarini** [comment]
to me any technology is good as long as the build could run as github page [more info](https://pages.github.com/) in the `gh-pages` branch

**Comment by aMarCruz** [comment]
@prateekbh , I think it's better to keep the riot tools with minimal dependencies so users are not forced to install additional frameworks, flux is ok.

**Comment by prateekbh** [comment]
we are moving forward with static data and core riot router...
as the project grows and demands... we'll add stuff eventually
