### ISSUE TITLE
Make Right Drawer

### ISSUE THREAD

**Issue by prateekbh** [riot/made-with-riot#3]
We need a semi transparent right drawer which is supposed to open in desktop when "View details button" is clicked
and this becomes fullscreen when on mobile

**Comment by prateekbh** [comment]
add close buton on top

**Comment by gregorypratt** [comment]
Would this be useful? http://riotgear.js.org/components/drawer/

**Comment by GianlucaGuarini** [comment]
I think they made it http://riotjs.com/made-with-riot/#/details/2
