### ISSUE TITLE
Update to riot3

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/made-with-riot#39]
The site is still using an old riot version, it would be nice to see it updated

**Comment by kazzkiq** [comment]
Done.

Also, it seems that in v3 the `tags` word became "reserved" somehow. As it was not listed in the [Migration Guide](http://riotjs.com/guide/migration-from-riot2/) I'm not sure if its a bug or not.

Apparently, when you have a object with `tags` on it and try to use it on a component, riot interpret the `tags` as its own object. Example:

```html
<my-tag>
  <div each="{ movies }">
    <h1>{ name }</h1>
    <h2>{ tags }</h2>  <!-- riot ignores "movies.tags" and try to render it own "tags" object here -->
  </div>
  <script>
    this.movies = [{ name: 'The Matrix', tags: 'Action, Sci-fi, Tech' }]
  </script>
</my-tag>
```

A workaround I found for this is to simply use `object in objects` and make a explicit reference to any `tags` words. Using the above example:

```html
<my-tag>
  <div each="{ movie in movies }">
    <h1>{ movie.name }</h1>
    <h2>{ movie.tags }</h2>  <!-- now it works -->
  </div>
  <script>
    this.movies = [{ name: 'The Matrix', tags: 'Action, Sci-fi, Tech' }]
  </script>
</my-tag>
```

**Comment by GianlucaGuarini** [comment]
@kazzkiq well it worked before but it's not a bug. `tags` is a reserved word in riot and if you try to render it in your template you will now always get an object. Your second example seems to me the right way to deal with such kind of loops
