### ISSUE TITLE
[component] Finish top-bar component

### ISSUE THREAD

**Issue by kazzkiq** [riot/made-with-riot#5]
Todo list for this component:

- [x] Make it responsible for small devices
- [x] Make *offcanvas* action effect on small devices
- [x] Make search input work

I think for now this is it.

**Comment by kazzkiq** [comment]
The filtering approach I implemented use CSS and attribute selectors. May not be the most elegant way to filter a list, but sure is the fastest and the simplest. [Borrowed from here](https://jets.js.org/).

**Comment by prateekbh** [comment]
cool... will work on it once all functionality is in place

**Comment by kazzkiq** [comment]
Mobile menu finished. Commit: 86c6021
