### ISSUE TITLE
[component] Finish card-list component

### ISSUE THREAD

**Issue by kazzkiq** [riot/made-with-riot#6]
Todo list for this component:

- [x] Make it responsible for small devices

As the functionality remains the same on large and small devices, there is no much left to do on this one.

**Comment by prateekbh** [comment]
what are we using to make ajax calls???
vanilla js?

**Comment by cognitom** [comment]
@prateekbh how about starting from something like this?
https://github.com/riot/riot/blob/v2.3.13/lib/browser/compiler/compile.js#L12-L23

**Comment by prateekbh** [comment]
@cognitom riot has a GET method??

**Comment by prateekbh** [comment]
oh no wait... r u suggesting a vanilla js approach?

**Comment by cognitom** [comment]
Yeah. Riot has GET method but it's private.

**Comment by rsbondi** [comment]
I have expanded the riot internals into a [mixin](http://plnkr.co/edit/SZAfbt?p=preview) if that is helpful.  It should be easy enough to adapt to POST also if needed.

**Comment by prateekbh** [comment]
@rsbondi that seems helpful.. thanks :+1:

**Comment by kazzkiq** [comment]
Will be migrating the Ajax thread to own Issue: #8
