### ISSUE TITLE
breakpoints for RWD

### ISSUE THREAD

**Issue by prateekbh** [riot/made-with-riot#7]
what the responsive screen breakpoints that we are setting here in this project?

**Comment by rsbondi** [comment]
It would make sense to follow [bootstrap](http://getbootstrap.com/css/#grid) or [foundation](http://foundation.zurb.com/sites/docs/v/5.5.3/media-queries.html)

**Comment by kazzkiq** [comment]
I think we could follow Bootstrap breakpoints.

**Comment by kazzkiq** [comment]
Commit 83248cd adds mixins and variables based on Bootstrap breakpoints.

I just made a small change on large breakpoint value for better fidelity with the initial design on bigger screens (1200px seems small for larger screens)
