### ISSUE TITLE
Showcasing riot tags

### ISSUE THREAD

**Issue by amitguptagwl** [riot/made-with-riot#70]
Do we some place to showcase riot custom components / tags instead of complete application? Please share the detail.

riot tag for [typewriter](https://github.com/amitguptagwl/web-snippets/tree/master/riotjs-components/typewriter) effect

**Comment by k-kuwahara** [comment]
@amitguptagwl 
As far as I know, I have not seen it. An example of `typewriter` is wonderful!

**Comment by prateekbh** [comment]
https://github.com/riot/riot#components

**Comment by amitguptagwl** [comment]
Thanks @k-kuwahara and @prateekbh . I've raised a PR.
