### ISSUE TITLE
Define approach for making Ajax calls

### ISSUE THREAD

**Issue by kazzkiq** [riot/made-with-riot#8]
Should we use some micro-library? Vanilla JS? Just a wrapper?

Migrated from discussion on #6

**Comment by prateekbh** [comment]
a promise based approach as shown by @rsbondi would be best.. cuz in that case right drawer can query the same promise... for the detailed data

**Comment by rsbondi** [comment]
I used the word 'promise' in my example mixin, but I am not sure it should be called that, people may have different expectations from what it does.

**Comment by prateekbh** [comment]
ok then lets evaluate it a lil more.. cuz the same data is needed by the right drawer as well...
and would be needed in the very beginning...
before drawers and card lists can render...

**Comment by prateekbh** [comment]
we build this with a promise polyfill...
this can be closed now
